apiVersion: v1
kind: Service
metadata: 
  name: mongo-express-svc
  namespace: default
spec: 
  selector:
    app: mongo-express
  type: NodePort
  ports:
   - port: 8081
     targetPort: 8081
     nodePort: 32323