apiVersion: v1
kind: Service
metadata: 
  name: mongo-svc
  namespace: default
spec: 
  selector:
    app: mongodb
  type: NodePort
  ports:
   - port: 27017
     targetPort: 27017
     nodePort: 32321