apiVersion: v1
kind: Pod 
metadata:
  name: mongodb
  namespace: default
  labels:
    env: mongodb
spec:
  containers:
    - name: mongodb-container
      image: mongo
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: hodi
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: hodi



#docker run --name -e MONGO_INITDB_ROOT_USERNAME=hodi -e MONGO_INITDB_ROOT_PASSWORD=hodi mongo