apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
             - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_AUTH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-cm
                  key: admin-username
            - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: admin-password
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo-svc
              # valueFrom:
              #   configMapKeyRef:
              #     name: mongo-cm
              #     key: database-host
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: yuval
              # valueFrom:
              #   configMapKeyRef:
              #     name: mongo-cm
              #     key: admin-username
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: shay
              # valueFrom:
              #   secretKeyRef:
              #     name: mongo-secret
              #     key: admin-password
  replicas: 2
  selector:
   matchLabels:
     app: mongo-express